//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcwebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postcode
    {
        public int ID { get; set; }
        public int PostCode1 { get; set; }
        public string Locality { get; set; }
        public string State { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public System.Data.Spatial.DbGeography MapRef { get; set; }
    }
}
